config:
  ipv4.address: 10.121.5.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:a2fa:6b11:c997::1/64
  ipv6.nat: "true"
description: ""
name: kube-net
type: bridge
used_by:
- /1.0/containers/kube-master?project=kubeadm-test
- /1.0/containers/kube-node1?project=kubeadm-test
- /1.0/containers/kube-node2?project=kubeadm-test
managed: true
status: Created
locations:
- none
